[package]
name = "iter-n-gen"
version = "0.1.0"
edition = "2021"
publish = false

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.82"
syn = { version = "2.0.60", features = ["full"] }
proc-macro2 = "1.0.81"
quote = "1.0.36"
